# Generated by Django 5.0.3 on 2024-04-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rating", models.FloatField()),
                ("table_booking", models.BooleanField(default=False)),
                ("online_delivery", models.BooleanField(default=False)),
                ("country_code", models.CharField(max_length=10)),
                ("city_code", models.CharField(max_length=10)),
                (
                    "Cuisines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="restaurants.cuisine",
                    ),
                ),
                ("cuisines", models.ManyToManyField(to="restaurants.cuisine")),
            ],
        ),
    ]
